[build]
  command = "chmod +x node_modules/.bin/ng && ng build --prod"
  publish = "dist/cricket-fee-distributor-v2"

[[plugins]]
  package = "@netlify/angular-runtime"

[build.environment]
  NODE_VERSION = "18"